// Lunarist Slides + Price/Slides feature.
// Data shape:
// service.slide_pricing = [{min_slides,max_slides,price,currency,label}]
// project.slides = [{id,type,url,title,description,position,duration}]
(function(){
  if(typeof window==='undefined'||window.__lunaristSlidesPricingInstalled)return;
  window.__lunaristSlidesPricingInstalled=true;
  const money=(v,c='USD')=>{const n=Number(v);if(!Number.isFinite(n))return '—';try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:2}).format(n)}catch{return `${c} ${n.toFixed(2)}`}};
  window.LunaristSlidesPricing={
    calculate(service,slideCount){const n=Math.max(0,Number(slideCount)||0);const rows=Array.isArray(service?.slide_pricing)?service.slide_pricing:[];if(!rows.length)return null;const row=rows.find(x=>n>=Number(x.min_slides||0)&&(x.max_slides==null||x.max_slides===''||n<=Number(x.max_slides)));if(!row)return null;return {price:Number(row.price)||0,currency:row.currency||service.currency||'USD',label:row.label||`${row.min_slides}${row.max_slides?'–'+row.max_slides:'+'} slides`};},
    total(service,slideCount){const base=this.calculate(service,slideCount);if(!base)return null;return {...base,formatted:money(base.price,base.currency)};}
  };
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function injectStyle(){if(document.getElementById('lunarist-slides-style'))return;const s=document.createElement('style');s.id='lunarist-slides-style';s.textContent='.slide-pricing-box{border:1px solid var(--line);background:rgba(255,255,255,.03);border-radius:16px;padding:14px;margin-top:12px}.slide-pricing-row{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:8px;align-items:end;margin-top:8px}.slide-pricing-row input,.slide-pricing-row select{min-width:0;border:1px solid var(--line);background:#0a0910;color:var(--text);padding:9px;border-radius:9px}.slide-pricing-remove{border:1px solid rgba(255,125,142,.3);background:rgba(255,125,142,.08);color:var(--danger);padding:9px;border-radius:9px}@media(max-width:600px){.slide-pricing-row{grid-template-columns:1fr 1fr}.slide-pricing-remove{grid-column:1/-1}}.project-slides-box{margin-top:14px}.project-slides-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:10px}.project-slide{position:relative;border:1px solid var(--line);border-radius:12px;overflow:hidden;background:#08070d}.project-slide img,.project-slide video{width:100%;aspect-ratio:16/10;object-fit:cover;display:block}.project-slide-body{padding:9px}.project-slide-title{font-weight:800;font-size:12px}.project-slide-desc{font-size:11px;color:var(--muted);margin-top:3px}.project-slide-num{position:absolute;left:7px;top:7px;background:rgba(0,0,0,.7);padding:4px 7px;border-radius:999px;font-size:10px}@media(max-width:720px){.project-slides-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}';document.head.appendChild(s);}
  function servicePricingEditor(host,rows=[],currency='USD'){if(!host)return;host.innerHTML=`<div class="slide-pricing-box"><div class="row"><div class="grow"><strong>Price / Slides</strong><div class="meta">Set a price for each slide-count range.</div></div><button type="button" class="btn" data-slide-price-add>+ Add range</button></div><div data-slide-price-rows></div></div>`;const wrap=host.querySelector('[data-slide-price-rows]');const add=(r={})=>{const el=document.createElement('div');el.className='slide-pricing-row';el.innerHTML=`<div class="field"><label>Min slides</label><input type="number" min="1" step="1" value="${esc(r.min_slides||1)}" data-sp-min></div><div class="field"><label>Max slides</label><input type="number" min="1" step="1" placeholder="∞" value="${esc(r.max_slides??'')}" data-sp-max></div><div class="field"><label>Price (${esc(currency)})</label><input type="number" min="0" step="0.01" value="${esc(r.price??0)}" data-sp-price></div><button type="button" class="slide-pricing-remove" data-sp-remove>Remove</button>`;wrap.appendChild(el);};(rows.length?rows:[{min_slides:1,max_slides:5,price:0,currency}]).forEach(add);host.querySelector('[data-slide-price-add]').onclick=()=>add({min_slides:(rows.at(-1)?.max_slides||0)+1,currency});wrap.addEventListener('click',e=>{if(e.target.closest('[data-sp-remove]'))e.target.closest('.slide-pricing-row').remove();});host.getValue=()=>[...wrap.querySelectorAll('.slide-pricing-row')].map(el=>({min_slides:Math.max(1,Number(el.querySelector('[data-sp-min]').value)||1),max_slides:el.querySelector('[data-sp-max]').value===''?null:Math.max(1,Number(el.querySelector('[data-sp-max]').value)||1),price:Math.max(0,Number(el.querySelector('[data-sp-price]').value)||0),currency}));return host;}
  window.LunaristSlidesPricing.mountServiceEditor=servicePricingEditor;
  window.LunaristSlidesPricing.mountProjectSlides=function(host,slides=[]){injectStyle();if(!host)return;host.classList.add('project-slides-box');host.innerHTML=`<div class="row"><div class="grow"><strong>Project Slides</strong><div class="meta">Add images, videos, or other visual pages to this project.</div></div><input type="file" accept="image/*,video/*" multiple data-project-slides-files></div><div class="project-slides-grid" data-project-slides-grid></div>`;const grid=host.querySelector('[data-project-slides-grid]');const list=Array.isArray(slides)?slides.map((x,i)=>({...x,position:x.position??i+1})):[];const render=()=>{grid.innerHTML=list.map((x,i)=>{const visual=x.type==='video'?`<video src="${esc(x.url)}" muted playsinline></video>`:`<img src="${esc(x.url)}" alt="${esc(x.title||`Slide ${i+1}`)}">`;return `<article class="project-slide"><span class="project-slide-num">${i+1}</span>${visual}<div class="project-slide-body"><div class="project-slide-title">${esc(x.title||`Slide ${i+1}`)}</div>${x.description?`<div class="project-slide-desc">${esc(x.description)}</div>`:''}</div></article>`;}).join('')||'<div class="empty" style="grid-column:1/-1;padding:25px">No slides yet.</div>';};host.getValue=()=>list.map((x,i)=>({...x,position:i+1}));host.addSlides=(items)=>{list.push(...items.map((x,i)=>({...x,position:list.length+i+1,id:x.id||crypto.randomUUID?.()||String(Date.now()+i)})));render();};host.querySelector('[data-project-slides-files]').addEventListener('change',e=>{const files=[...e.target.files];host.addSlides(files.map((f,i)=>({id:crypto.randomUUID?.()||String(Date.now()+i),type:f.type.startsWith('video/')?'video':'image',url:URL.createObjectURL(f),title:f.name.replace(/\.[^.]+$/,''),description:''})));});render();return host;};
  injectStyle();
})();
