// Lunarist: make Price/Slides and multi-file Project Slides visible and persistent.
(function(){
  if(typeof window==='undefined'||window.__lunaristSlidesLiveUI)return;
  window.__lunaristSlidesLiveUI=true;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=(v)=>{const n=Number(v)||0;try{return new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n)}catch{return '$'+n.toFixed(2)}};
  const q=s=>document.querySelector(s);
  const qa=s=>[...document.querySelectorAll(s)];
  let serviceRows=[];
  let projectSlides=[];
  let projectId='';
  let busy=false;

  function styles(){if(q('#lunarist-slides-live-style'))return;const s=document.createElement('style');s.id='lunarist-slides-live-style';s.textContent=`.ls-price-panel,.ls-project-slides{border:1px solid var(--line);border-radius:18px;background:linear-gradient(180deg,rgba(255,255,255,.045),rgba(255,255,255,.018));padding:16px;margin-top:14px}.ls-price-head,.ls-slides-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.ls-kicker{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:var(--gold);font-weight:800}.ls-help{font-size:12px;color:var(--muted);margin-top:3px}.ls-price-row{display:grid;grid-template-columns:1fr 1fr 1.2fr auto;gap:9px;align-items:end;margin-top:10px;padding:11px;border:1px solid var(--line);border-radius:13px;background:rgba(0,0,0,.12)}.ls-price-row .field input{width:100%}.ls-remove{height:42px;border:1px solid rgba(255,125,142,.28);background:rgba(255,125,142,.08);color:var(--danger);border-radius:10px;padding:0 12px}.ls-preview{margin-top:10px;padding:10px 12px;border:1px dashed var(--line);border-radius:11px;color:var(--muted);font-size:12px}.ls-preview b{color:var(--text)}.ls-multi-wrap{margin-top:12px;padding:13px;border:1px dashed var(--line);border-radius:13px;background:rgba(255,255,255,.02)}.ls-multi-wrap input[type=file]{width:100%;max-width:100%}.ls-selected{margin-top:10px;color:var(--muted);font-size:12px}.ls-slides-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:12px}.ls-slide{position:relative;border:1px solid var(--line);border-radius:13px;overflow:hidden;background:#08070d}.ls-slide-media{aspect-ratio:16/10;background:#000}.ls-slide-media img,.ls-slide-media video{display:block;width:100%;height:100%;object-fit:cover}.ls-slide-body{padding:10px}.ls-slide-body input,.ls-slide-body textarea{width:100%;max-width:100%;border:1px solid var(--line);background:#0a0910;color:var(--text);border-radius:9px;padding:8px;margin-top:5px}.ls-slide-body textarea{min-height:55px;resize:vertical}.ls-slide-top{position:absolute;left:7px;right:7px;top:7px;display:flex;justify-content:space-between;gap:5px}.ls-num{background:rgba(0,0,0,.72);color:#fff;border-radius:999px;padding:4px 7px;font-size:10px;font-weight:800}.ls-del{border:1px solid rgba(255,125,142,.35);background:rgba(0,0,0,.7);color:#fff;border-radius:999px;padding:4px 8px}.ls-slide-tools{display:flex;gap:5px;margin-top:7px}.ls-slide-tools button{flex:1;padding:7px;border:1px solid var(--line);background:rgba(255,255,255,.04);color:var(--text);border-radius:8px;font-size:11px}.ls-empty{color:var(--muted);font-size:12px;padding:16px 0}@media(max-width:700px){.ls-price-row{grid-template-columns:1fr 1fr}.ls-price-row .ls-remove{grid-column:1/-1}.ls-slides-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.appendChild(s)}
  async function waitClient(){for(let i=0;i<30;i++){if(window.supabaseClient&&window.state?.currentUser)return true;await new Promise(r=>setTimeout(r,150));}return false}
  async function loadProjectSlides(id){if(!id||!window.supabaseClient)return [];try{const r=await supabaseClient.from('projects').select('id,slides').eq('id',id).maybeSingle();return r.error?[]:(Array.isArray(r.data?.slides)?r.data.slides:[])}catch{return []}}
  async function loadServicePricing(title){if(!title||!window.supabaseClient)return [];try{const r=await supabaseClient.from('services').select('id,title,slide_pricing').eq('title',title).maybeSingle();return r.error?[]:(Array.isArray(r.data?.slide_pricing)?r.data.slide_pricing:[])}catch{return []}}
  async function upload(file,kind){if(typeof window.uploadProjectFile==='function')return window.uploadProjectFile(file,kind);if(!window.supabaseClient||!window.state?.currentUser)throw Error('Storage is not ready.');const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${state.currentUser.id}/${crypto.randomUUID()}-${kind}.${ext}`;const up=await supabaseClient.storage.from('project-media').upload(path,file,{upsert:false,contentType:file.type||undefined});if(up.error)throw up.error;return supabaseClient.storage.from('project-media').getPublicUrl(path).data.publicUrl}
  function getProjectIdFromForm(){const f=q('#projectForm');if(f?.dataset.lsProjectId)return f.dataset.lsProjectId;const title=q('#pjTitle')?.value.trim();if(title&&Array.isArray(window.data?.projects)){const p=data.projects.find(x=>x.title===title&&x.member===state.currentUser?.id);if(p)return p.id}return projectId}
  function mountPrice(){const form=q('#serviceForm');if(!form||q('#lsPriceSlidesPanel'))return;styles();const anchor=q('#addonContainer')?.closest('.field')||form.querySelector('.service-addons-field')||form.querySelector('.formgrid');if(!anchor)return;const box=document.createElement('div');box.id='lsPriceSlidesPanel';box.className='field full';box.innerHTML='<div class="ls-price-panel"><div class="ls-price-head"><div><div class="ls-kicker">Price / Slides</div><div class="ls-help">Set exactly how much clients pay for each slide-count range.</div></div><button type="button" class="btn" id="lsAddPriceRange">+ Add slide range</button></div><div id="lsPriceRows"></div><div class="ls-preview">Example: <b>1–5 slides = $50</b>, <b>6–10 slides = $90</b>. Use an empty Max for an unlimited range.</div></div>';anchor.parentNode.insertBefore(box,anchor.nextSibling);const rows=q('#lsPriceRows');const add=(r={})=>{const el=document.createElement('div');el.className='ls-price-row';el.innerHTML=`<div class="field"><label>Min slides</label><input type="number" min="1" value="${esc(r.min_slides??1)}" data-ls-min></div><div class="field"><label>Max slides</label><input type="number" min="1" value="${esc(r.max_slides??'')}" placeholder="Unlimited" data-ls-max></div><div class="field"><label>Price per range</label><input type="number" min="0" step="0.01" value="${esc(r.price??0)}" placeholder="$50" data-ls-price></div><button type="button" class="ls-remove" data-ls-remove>Remove</button>`;rows.appendChild(el)};(serviceRows.length?serviceRows:[{min_slides:1,max_slides:5,price:0}]).forEach(add);q('#lsAddPriceRange').onclick=()=>add({min_slides:(Math.max(0,...qa('[data-ls-max]').map(x=>Number(x.value)||0))+1),max_slides:'',price:0});rows.addEventListener('click',e=>{const b=e.target.closest('[data-ls-remove]');if(b)b.parentElement.remove()});}
  function priceValue(){return qa('#lsPriceRows .ls-price-row').map(r=>({min_slides:Math.max(1,Number(r.querySelector('[data-ls-min]').value)||1),max_slides:r.querySelector('[data-ls-max]').value===''?null:Math.max(1,Number(r.querySelector('[data-ls-max]').value)||1),price:Math.max(0,Number(r.querySelector('[data-ls-price]').value)||0),currency:'USD'})).sort((a,b)=>a.min_slides-b.min_slides)}
  async function persistService(){if(!window.supabaseClient||!state.currentUser)return;const title=q('#svTitle')?.value.trim();if(!title)return;const rows=priceValue();try{const r=await supabaseClient.from('services').update({slide_pricing:rows,updated_at:new Date().toISOString()}).eq('owner_id',state.currentUser.id).eq('title',title);if(r.error)throw r.error;const s=data?.services?.find(x=>x.title===title);if(s)s.slide_pricing=rows;toast?.('Price / Slides saved.')}catch(e){toast?.('Could not save Price / Slides: '+e.message)}}
  function mountProject(){const form=q('#projectForm');if(!form||q('#lsProjectSlides'))return;styles();projectId=form.dataset.lsProjectId||'';const anchor=q('#pjMediaFile')?.closest('.field')||q('#pjMedia')?.closest('.field');if(!anchor)return;const box=document.createElement('div');box.id='lsProjectSlides';box.className='field full';box.innerHTML='<div class="ls-project-slides"><div class="ls-slides-head"><div><div class="ls-kicker">Project Slides</div><div class="ls-help">Upload multiple images/videos. Each file becomes a slide in this project.</div></div><span class="addon-count-badge" id="lsSlideCount">0 slides</span></div><div class="ls-multi-wrap"><input id="lsSlidesFiles" type="file" accept="image/*,video/*" multiple><div class="ls-selected" id="lsSlideStatus">You can select multiple files at once.</div></div><div class="ls-slides-grid" id="lsSlidesGrid"></div></div>';anchor.parentNode.insertBefore(box,anchor.nextSibling);renderSlides();q('#lsSlidesFiles').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;const status=q('#lsSlideStatus');status.textContent=`Uploading ${files.length} slide${files.length===1?'':'s'}…`;for(const f of files){try{const url=await upload(f,'slide');projectSlides.push({id:crypto.randomUUID(),type:f.type.startsWith('video/')?'video':'image',url,title:f.name.replace(/\.[^.]+$/,''),description:'',position:projectSlides.length+1})}catch(err){toast?.('Slide upload failed: '+err.message)}}e.target.value='';renderSlides();status.textContent=`${projectSlides.length} slide${projectSlides.length===1?'':'s'} ready. Save the project to keep them.`;});}
  function renderSlides(){const g=q('#lsSlidesGrid'),count=q('#lsSlideCount');if(!g)return;if(count)count.textContent=`${projectSlides.length} slide${projectSlides.length===1?'':'s'}`;g.innerHTML=projectSlides.map((s,i)=>`<article class="ls-slide"><div class="ls-slide-top"><span class="ls-num">Slide ${i+1}</span><button type="button" class="ls-del" data-slide-del="${esc(s.id)}">×</button></div><div class="ls-slide-media">${s.type==='video'?`<video src="${esc(s.url)}" muted playsinline controls></video>`:`<img src="${esc(s.url)}" alt="Slide ${i+1}">`}</div><div class="ls-slide-body"><label class="field"><span class="ls-help">Title</span><input value="${esc(s.title||'')}" data-slide-title="${esc(s.id)}"></label><label class="field"><span class="ls-help">Description</span><textarea data-slide-desc="${esc(s.id)}">${esc(s.description||'')}</textarea></label><div class="ls-slide-tools"><button type="button" data-slide-up="${esc(s.id)}">↑ Move</button><button type="button" data-slide-down="${esc(s.id)}">↓ Move</button></div></div></article>`).join('')||'<div class="ls-empty" style="grid-column:1/-1">No project slides yet.</div>';
    qa('[data-slide-del]').forEach(b=>b.onclick=()=>{projectSlides=projectSlides.filter(x=>String(x.id)!==String(b.dataset.slideDel));renderSlides()});qa('[data-slide-up]').forEach(b=>b.onclick=()=>moveSlide(b.dataset.slideUp,-1));qa('[data-slide-down]').forEach(b=>b.onclick=()=>moveSlide(b.dataset.slideDown,1));qa('[data-slide-title]').forEach(i=>i.oninput=()=>{const s=projectSlides.find(x=>String(x.id)===String(i.dataset.slideTitle));if(s)s.title=i.value});qa('[data-slide-desc]').forEach(i=>i.oninput=()=>{const s=projectSlides.find(x=>String(x.id)===String(i.dataset.slideDesc));if(s)s.description=i.value});}
  function moveSlide(id,delta){const i=projectSlides.findIndex(x=>String(x.id)===String(id)),j=i+delta;if(i<0||j<0||j>=projectSlides.length)return;[projectSlides[i],projectSlides[j]]=[projectSlides[j],projectSlides[i]];renderSlides()}
  async function persistProject(){if(!window.supabaseClient||!state.currentUser)return;const title=q('#pjTitle')?.value.trim();if(!title)return;const slides=projectSlides.map((x,i)=>({...x,position:i+1}));let targetId=getProjectIdFromForm();for(let i=0;i<8&&!targetId;i++){try{const r=await supabaseClient.from('projects').select('id').eq('owner_id',state.currentUser.id).eq('title',title).order('created_at',{ascending:false}).limit(1).maybeSingle();targetId=r.data?.id||''}catch{}if(!targetId)await new Promise(r=>setTimeout(r,400))}if(!targetId){toast?.('Project saved, but its Slides could not be attached yet. Open Edit and save again.');return}try{const r=await supabaseClient.from('projects').update({slides,updated_at:new Date().toISOString()}).eq('id',targetId).eq('owner_id',state.currentUser.id);if(r.error)throw r.error;projectId=targetId;const p=data?.projects?.find(x=>x.id===targetId);if(p)p.slides=slides;toast?.('Project Slides saved.')}catch(e){toast?.('Could not save Project Slides: '+e.message)}}
  async function scan(){if(busy)return;busy=true;try{if(!q('#serviceForm')&&!q('#projectForm'))return;const sf=q('#serviceForm');if(sf&&!q('#lsPriceSlidesPanel')){const title=q('#svTitle')?.value.trim();serviceRows=await loadServicePricing(title);mountPrice();const btn=q('#saveService');if(btn&&!btn.dataset.lsSlideBound){btn.dataset.lsSlideBound='1';btn.addEventListener('click',()=>setTimeout(persistService,700),false)}}const pf=q('#projectForm');if(pf&&!q('#lsProjectSlides')){projectId=pf.dataset.lsProjectId||'';projectSlides=await loadProjectSlides(projectId);mountProject();const btn=q('#saveProject');if(btn&&!btn.dataset.lsSlideBound){btn.dataset.lsSlideBound='1';btn.addEventListener('click',()=>setTimeout(persistProject,900),false)}}}finally{busy=false}}
  const obs=new MutationObserver(()=>{clearTimeout(obs.t);obs.t=setTimeout(scan,50)});obs.observe(document.body,{childList:true,subtree:true});scan();
})();
