import crypto from 'node:crypto';

const EUGENE_ORIGIN='https://eugene-card-1.vercel.app';
const CLIENT_ID='lunarist-studio';
const CALLBACK='https://lunaristudio.vercel.app/api/eugene-card/callback';
const AUTH_ENDPOINT=`${EUGENE_ORIGIN}/api/oauth/authorize`;
const TOKEN_ENDPOINT=`${EUGENE_ORIGIN}/api/oauth/token`;
const USERINFO_ENDPOINT=`${EUGENE_ORIGIN}/api/oauth/userinfo`;
const REVOKE_ENDPOINT=`${EUGENE_ORIGIN}/api/oauth/revoke`;
const SCOPES='openid profile email offline_access';
const COOKIE='lunarist_eugene_oauth';
const TTL=10*60*1000;
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const random=()=>crypto.randomBytes(32).toString('base64url');
const b64=v=>Buffer.from(v).toString('base64url');
const unb64=v=>Buffer.from(String(v),'base64url').toString('utf8');
const sbHeaders=key=>({apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json'});
const jsonHeaders=key=>({...sbHeaders(key),'Content-Type':'application/json'});
function sign(payload,key){const body=b64(JSON.stringify(payload));const sig=crypto.createHmac('sha256',key).update(body).digest('base64url');return `${body}.${sig}`}
function verify(value,key){try{const [body,sig]=String(value||'').split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',key).update(body).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const p=JSON.parse(unb64(body));return p?.exp>Date.now()?p:null}catch{return null}}
function setCookie(res,value,maxAge){res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`)}
function clearCookie(res){setCookie(res,'',0)}
function getCookie(req){for(const part of String(req.headers.cookie||'').split(';')){const [k,...v]=part.trim().split('=');if(k===COOKIE)return decodeURIComponent(v.join('='))}return''}
async function userFromToken(url,key,token){if(!token)return null;const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});if(!r.ok)return null;return r.json().catch(()=>null)}
async function rest(url,key,path,options={}){const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{...sbHeaders(key),...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}return{ok:r.ok,status:r.status,data}}
function deriveKey(key){return crypto.createHash('sha256').update(String(key)).digest()}
function encrypt(value,key){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',deriveKey(key),iv);const data=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);const tag=cipher.getAuthTag();return Buffer.concat([iv,tag,data]).toString('base64url')}
function decrypt(value,key){try{const raw=Buffer.from(String(value),'base64url');const iv=raw.subarray(0,12),tag=raw.subarray(12,28),data=raw.subarray(28);const decipher=crypto.createDecipheriv('aes-256-gcm',deriveKey(key),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString('utf8')}catch{return''}}
function parseBody(req){if(req.body&&typeof req.body==='object')return req.body;try{return Object.fromEntries(new URLSearchParams(String(req.body||'')))}catch{return{}}}
async function exchange(code,verifier,url,key){const body=new URLSearchParams({grant_type:'authorization_code',client_id:CLIENT_ID,redirect_uri:CALLBACK,code,code_verifier:verifier});if(process.env.EUGENE_CLIENT_SECRET)body.set('client_secret',process.env.EUGENE_CLIENT_SECRET);const r=await fetch(TOKEN_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body});const data=await r.json().catch(()=>({}));if(!r.ok||!data.access_token)throw new Error(data.error_description||data.error||'Eugene Card token exchange failed.');return data}
async function userinfo(access){const r=await fetch(USERINFO_ENDPOINT,{headers:{Authorization:`Bearer ${access}`,Accept:'application/json'}});const data=await r.json().catch(()=>({}));if(!r.ok||!data.sub)throw new Error(data.error_description||data.error||'Eugene Card identity lookup failed.');return data}
async function saveConnection(url,key,lunaristUserId,profile,tokens){const now=Date.now();const expiresIn=Number(tokens.expires_in||900),refreshExpiresIn=Number(tokens.refresh_expires_in||30*24*60*60);const row={lunarist_user_id:lunaristUserId,eugene_uid:String(profile.sub),eugene_email:profile.email||null,connected_at:new Date(now).toISOString(),last_seen_at:new Date(now).toISOString(),profile_url:profile.profile_url||profile.url||null,encrypted_access_token:encrypt(tokens.access_token,key),encrypted_refresh_token:tokens.refresh_token?encrypt(tokens.refresh_token,key):null,access_expires_at:new Date(now+expiresIn*1000).toISOString(),refresh_expires_at:tokens.refresh_token?new Date(now+refreshExpiresIn*1000).toISOString():null,scope:String(tokens.scope||SCOPES),revoked_at:null,token_type:String(tokens.token_type||'Bearer')};const r=await rest(url,key,`eugene_card_connections?lunarist_user_id=eq.${encodeURIComponent(lunaristUserId)}`,{method:'PATCH',headers:{...jsonHeaders(key),Prefer:'return=representation'},body:JSON.stringify(row)});if(!r.ok||!Array.isArray(r.data)||!r.data.length){const created=await rest(url,key,'eugene_card_connections',{method:'POST',headers:{...jsonHeaders(key),Prefer:'return=representation'},body:JSON.stringify(row)});if(!created.ok)throw new Error('OAuth succeeded but Lunarist could not store the Eugene Card connection.')}return row}
async function refreshRow(url,key,row){const refresh=decrypt(row.encrypted_refresh_token,key);if(!refresh)throw new Error('Eugene Card refresh token is unavailable.');const body=new URLSearchParams({grant_type:'refresh_token',client_id:CLIENT_ID,refresh_token:refresh});if(process.env.EUGENE_CLIENT_SECRET)body.set('client_secret',process.env.EUGENE_CLIENT_SECRET);const r=await fetch(TOKEN_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body});const data=await r.json().catch(()=>({}));if(!r.ok||!data.access_token)throw new Error(data.error_description||data.error||'Eugene Card token refresh failed.');const now=Date.now();const next={encrypted_access_token:encrypt(data.access_token,key),encrypted_refresh_token:data.refresh_token?encrypt(data.refresh_token,key):row.encrypted_refresh_token,access_expires_at:new Date(now+Number(data.expires_in||900)*1000).toISOString(),refresh_expires_at:data.refresh_token?new Date(now+Number(data.refresh_expires_in||30*24*60*60)*1000).toISOString():row.refresh_expires_at,last_seen_at:new Date(now).toISOString(),revoked_at:null};const saved=await rest(url,key,`eugene_card_connections?id=eq.${encodeURIComponent(row.id)}`,{method:'PATCH',headers:{...jsonHeaders(key),Prefer:'return=representation'},body:JSON.stringify(next)});if(!saved.ok)throw new Error('Refreshed Eugene Card token could not be stored.');return {...row,...next}}
function html(message,success=false){const safe=String(message||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="2;url=/"><title>Eugene Card · Lunarist</title><style>body{margin:0;min-height:100vh;background:#08070d;color:#f7f4ff;font:16px system-ui;display:grid;place-items:center}.card{width:min(520px,90vw);padding:30px;background:#111019;border:1px solid rgba(255,255,255,.1);border-radius:22px;text-align:center}.ok{color:#8ee0ba}.err{color:#ff7d8e}p{color:#9c96ad;line-height:1.6}</style></head><body><main class="card"><div class="eyebrow">LUNARIST × EUGENE CARD</div><h1 class="${success?'ok':'err'}">${success?'Connected':'Connection failed'}</h1><p>${safe}</p><p>Returning to Lunarist…</p></main></body></html>`}
export async function start(req,res,url,key){const auth=String(req.headers.authorization||'');const token=auth.startsWith('Bearer ')?auth.slice(7):'';const user=await userFromToken(url,key,token);if(!user?.id)return res.status(401).json({error:'Sign in to Lunarist first.'});const verifier=random(),challenge=crypto.createHash('sha256').update(verifier).digest('base64url'),state=sign({uid:user.id,verifier,nonce:random(),exp:Date.now()+TTL},key);setCookie(res,state,Math.floor(TTL/1000));const u=new URL(AUTH_ENDPOINT);u.searchParams.set('response_type','code');u.searchParams.set('client_id',CLIENT_ID);u.searchParams.set('redirect_uri',CALLBACK);u.searchParams.set('scope',SCOPES);u.searchParams.set('code_challenge',challenge);u.searchParams.set('code_challenge_method','S256');u.searchParams.set('state',state);return res.status(200).json({authorization_url:u.toString()})}
export async function callback(req,res,url,key){const q=req.query||{};const state=String(q.state||'');const code=String(q.code||'');if(q.error){clearCookie(res);return res.status(400).send(html(q.error_description||q.error,false))}const signed=verify(state,key),cookieState=getCookie(req);if(!signed||!cookieState||cookieState!==state||!code)return res.status(400).send(html('The OAuth state or authorization code is invalid. Please start the connection again.',false));try{const tokens=await exchange(code,signed.verifier,url,key);const profile=await userinfo(tokens.access_token);await saveConnection(url,key,signed.uid,profile,tokens);clearCookie(res);return res.status(200).send(html(`Connected to Eugene Card as ${profile.name||profile.email||profile.sub}.`,true))}catch(e){clearCookie(res);console.error(e);return res.status(502).send(html(e.message||'Eugene Card connection failed.',false))}}
async function currentRow(url,key,userId){const r=await rest(url,key,`eugene_card_connections?lunarist_user_id=eq.${encodeURIComponent(userId)}&revoked_at=is.null&select=*&limit=1`);return r.ok&&Array.isArray(r.data)?r.data[0]||null:null}
export async function status(req,res,url,key){const auth=String(req.headers.authorization||'');const token=auth.startsWith('Bearer ')?auth.slice(7):'';const user=await userFromToken(url,key,token);if(!user?.id)return res.status(401).json({error:'Sign in is required.'});let row=await currentRow(url,key,user.id);if(!row)return res.status(200).json({connected:false,client_id:CLIENT_ID});if(row.access_expires_at&&new Date(row.access_expires_at)<=new Date()&&row.refresh_expires_at&&new Date(row.refresh_expires_at)>new Date()){try{row=await refreshRow(url,key,row)}catch(e){console.error(e)}}const connected=!!row&&!row.revoked_at&&((row.refresh_expires_at&&new Date(row.refresh_expires_at)>new Date())||(row.access_expires_at&&new Date(row.access_expires_at)>new Date()));return res.status(200).json({connected,client_id:CLIENT_ID,scope:row.scope||SCOPES,access_expires_at:row.access_expires_at||null,refresh_expires_at:row.refresh_expires_at||null,eugene_uid:row.eugene_uid||null,eugene_email:row.eugene_email||null})}
export async function revoke(req,res,url,key){const auth=String(req.headers.authorization||'');const token=auth.startsWith('Bearer ')?auth.slice(7):'';const user=await userFromToken(url,key,token);if(!user?.id)return res.status(401).json({error:'Sign in is required.'});const row=await currentRow(url,key,user.id);if(row){const access=decrypt(row.encrypted_access_token,key);const refresh=decrypt(row.encrypted_refresh_token,key);const tokenToRevoke=refresh||access;if(tokenToRevoke){try{const body=new URLSearchParams({client_id:CLIENT_ID,token:tokenToRevoke,token_type_hint:refresh?'refresh_token':'access_token'});if(process.env.EUGENE_CLIENT_SECRET)body.set('client_secret',process.env.EUGENE_CLIENT_SECRET);await fetch(REVOKE_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body})}catch(e){console.error(e)}}await rest(url,key,`eugene_card_connections?id=eq.${encodeURIComponent(row.id)}`,{method:'PATCH',headers:{...jsonHeaders(key),Prefer:'return=representation'},body:JSON.stringify({revoked_at:new Date().toISOString()})})}return res.status(200).json({connected:false,revoked:true})}
export async function handle(req,res,url,key){const action=String(req.query?.action||'status');if(action==='start')return start(req,res,url,key);if(action==='callback')return callback(req,res,url,key);if(action==='revoke')return revoke(req,res,url,key);return status(req,res,url,key)}
export const constants={EUGENE_ORIGIN,CLIENT_ID,CALLBACK,AUTH_ENDPOINT,TOKEN_ENDPOINT,USERINFO_ENDPOINT,REVOKE_ENDPOINT,SCOPES};
