function xParse(raw){const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);const h=u.hostname.toLowerCase().replace(/^www\./,'');if(!['x.com','twitter.com','mobile.twitter.com'].includes(h))throw new Error('That does not look like an X post URL.');const m=u.pathname.match(/\/(?:[^/]+)\/status\/(\d+)/i);if(!m)throw new Error('That does not look like an X post URL.');return m[1];}
const X_BEARER=process.env.X_WEB_BEARER?('Bearer '+String(process.env.X_WEB_BEARER).replace(/^Bearer\s+/i,'')):'';
const FALLBACK_IDS=[];
const xFeatures={creator_subscriptions_tweet_preview_api_enabled:true,premium_content_api_read_enabled:false,communities_web_enable_tweet_community_results_fetch:true,c9s_tweet_anatomy_moderator_badge_enabled:true,articles_preview_enabled:true,responsive_web_edit_tweet_api_enabled:true,graphql_is_translatable_rweb_tweet_is_translatable_enabled:true,view_counts_everywhere_api_enabled:true,longform_notetweets_consumption_enabled:true,responsive_web_twitter_article_tweet_consumption_enabled:true,freedom_of_speech_not_reach_fetch_enabled:true,standardized_nudges_misinfo:true,tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled:true,longform_notetweets_rich_text_read_enabled:true,longform_notetweets_inline_media_enabled:false,verified_phone_label_enabled:false,responsive_web_graphql_skip_user_profile_image_extensions_enabled:false,responsive_web_graphql_timeline_navigation_enabled:true,responsive_web_enhance_cards_enabled:false};
async function xQueryId(){try{const r=await fetch('https://x.com/',{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,application/xhtml+xml'}});if(!r.ok)return null;const h=await r.text();const m=h.match(/https:\/\/abs\.twimg\.com\/responsive-web\/client-web\/main\.([A-Za-z0-9_-]+)\.js/)||h.match(/\/responsive-web\/client-web\/main\.([A-Za-z0-9_-]+)\.js/);if(!m)return null;const r2=await fetch(`https://abs.twimg.com/responsive-web/client-web/main.${m[1]}.js`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r2.ok)return null;const j=await r2.text();return(j.match(/queryId:\"([^\"]+)\",operationName:\"TweetResultByRestId\"/)||j.match(/operationName:\"TweetResultByRestId\"[\s\S]{0,400}?queryId:\"([^\"]+)\"/))?.[1]||null;}catch{return null;}}
async function xViews(id,qid){try{const u=new URL(`https://x.com/i/api/graphql/${qid}/TweetResultByRestId`);u.searchParams.set('variables',JSON.stringify({tweetId:String(id),withCommunity:false,includePromotedContent:false,withVoice:false}));u.searchParams.set('features',JSON.stringify(xFeatures));u.searchParams.set('fieldToggles',JSON.stringify({withArticleRichContentState:true,withArticlePlainText:false,withGrokAnalyze:false,withDisallowedReplyControls:false}));const r=await fetch(u,{headers:{Authorization:X_BEARER,'x-twitter-active-user':'yes','x-twitter-client-language':'en','User-Agent':'Mozilla/5.0','Accept':'application/json','Referer':'https://x.com/'} });if(!r.ok)return null;const j=await r.json().catch(()=>null);const raw=j?.data?.tweetResult?.result;const t=raw?.tweet||raw;if(!t)return null;for(const v of[t.views?.count,t.views?.countString,t.legacy?.views?.count,t.legacy?.view_count]){const n=Number(String(v??'').replace(/,/g,''));if(Number.isFinite(n)&&n>=0)return n;}return null;}catch{return null;}}
export default async function handler(req,res){res.setHeader("Cache-Control","no-store");if(req.query?.xview){try{const id=xParse(req.query.url||'');const ids=[await xQueryId(),...FALLBACK_IDS].filter(Boolean);for(const qid of ids){const views=await xViews(id,qid);if(Number.isFinite(views))return res.status(200).json({ok:true,id,views,source:'x-web'});}return res.status(200).json({ok:false,id,views:null,source:'x-web'});}catch(e){return res.status(400).json({ok:false,error:e?.message||'Unable to fetch X views.'});}}
  const url=(process.env.SUPABASE_URL||"").replace(/\/$/,"");
  const anonKey=process.env.SUPABASE_ANON_KEY||"";
  if(!url||!anonKey)return res.status(503).json({error:"Missing SUPABASE_URL or SUPABASE_ANON_KEY"});
  return res.status(200).json({url,anonKey});
}
