// Lunarist Instagram fetcher + server-authoritative metric sync.
// Vercel env: INSTAGRAM_ACCESS_TOKEN
// Optional: META_APP_ID / META_APP_SECRET
function clean(v){return String(v||'').trim().replace(/^['"]|['"]$/g,'').replace(/^Bearer\s+/i,'').trim();}
function normalize(raw){const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);const h=u.hostname.toLowerCase().replace(/^www\./,'');if(h!=='instagram.com'&&h!=='instagr.am'&&!h.endsWith('.instagram.com'))throw new Error('That does not look like an Instagram URL.');if(!/(^|\/)(p|reel|reels|tv)\/[^/]+/i.test(u.pathname))throw new Error('Use an Instagram post, reel, or video URL.');return u.toString();}
function appToken(){const id=clean(process.env.META_APP_ID),secret=clean(process.env.META_APP_SECRET);return id&&secret?`${id}|${secret}`:'';}
function metaToken(){return clean(process.env.INSTAGRAM_ACCESS_TOKEN)||appToken();}
function metaUrl(url,token){const u=new URL(url);if(token)u.searchParams.set('access_token',token);return u;}
async function oembed(target,token){let u=metaUrl('https://graph.facebook.com/v25.0/instagram_oembed',token);u.searchParams.set('url',target);u.searchParams.set('maxwidth','658');u.searchParams.set('omitscript','true');let r=await fetch(u),d=await r.json().catch(()=>({}));if(!r.ok&&token){u=metaUrl('https://graph.facebook.com/v25.0/instagram_oembed','');u.searchParams.set('url',target);u.searchParams.set('maxwidth','658');u.searchParams.set('omitscript','true');r=await fetch(u);d=await r.json().catch(()=>({}));}return{r,d};}
async function pageMeta(target){try{const r=await fetch(target,{headers:{'user-agent':'Mozilla/5.0 (compatible; Lunarist/1.0)','accept':'text/html'},redirect:'follow'});const html=await r.text();const get=(name)=>{const esc=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const re=new RegExp(`<meta[^>]+(?:property|name)=[\"']${esc}[\"'][^>]+content=[\"']([^\"']*)[\"']|<meta[^>]+content=[\"']([^\"']*)[\"'][^>]+(?:property|name)=[\"']${esc}[\"']`,'i');const m=html.match(re);return m?.[1]||m?.[2]||'';};return{title:get('og:title'),description:get('og:description'),image:get('og:image'),video:get('og:video'),url:get('og:url')||target};}catch{return{title:'',description:'',image:'',video:'',url:target};}}
async function fetchMedia(mediaId,token){if(!mediaId||!token)return null;try{const fields='id,caption,media_type,media_product_type,media_url,thumbnail_url,permalink,timestamp,like_count,comments_count,view_count';const u=metaUrl(`https://graph.facebook.com/v25.0/${encodeURIComponent(mediaId)}`,token);u.searchParams.set('fields',fields);const r=await fetch(u),d=await r.json().catch(()=>({}));return r.ok?d:null;}catch{return null;}}
async function syncProject(projectId,target,mediaId,token){const base=clean(process.env.SUPABASE_URL),key=clean(process.env.SUPABASE_SERVICE_ROLE_KEY);if(!base||!key||!projectId||!target||!token)return false;const headers={apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json'};const lookup=await fetch(`${base}/rest/v1/projects?id=eq.${encodeURIComponent(projectId)}&select=id,media_url`,{headers});if(!lookup.ok)return false;const rows=await lookup.json().catch(()=>[]);const row=rows?.[0];if(!row)return false;let saved='';try{saved=normalize(row.media_url||'')}catch{}if(saved!==target)return false;let id=String(mediaId||'');if(!id){const {r,d}=await oembed(target,token);if(!r.ok)return false;id=String(d?.media_id||d?.id||'');}const media=await fetchMedia(id,clean(process.env.INSTAGRAM_ACCESS_TOKEN));if(!media)return false;const patch={};if(Number.isFinite(Number(media.like_count)))patch.likes=Math.max(0,Math.floor(Number(media.like_count)));if(Number.isFinite(Number(media.view_count)))patch.views=Math.max(0,Math.floor(Number(media.view_count)));if(!Object.keys(patch).length)return false;const updated=await fetch(`${base}/rest/v1/projects?id=eq.${encodeURIComponent(projectId)}`,{method:'PATCH',headers:{...headers,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});return updated.ok;}
export default async function handler(req,res){try{const raw=req.query?.url||req.body?.url||'';const target=normalize(raw);const token=metaToken();if(req.method==='POST'){if(!token)return res.status(503).json({ok:false,error:'Instagram API credentials are not configured.'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const projectId=String(body.projectId||'');const mediaId=String(body.mediaId||'');if(!projectId)return res.status(400).json({ok:false,error:'projectId is required.'});const ok=await syncProject(projectId,target,mediaId,token);return res.status(ok?200:400).json({ok});}
const {r,d}=await oembed(target,token);const pm=await pageMeta(target);if(!r.ok){const e=d?.error||{};const description=pm.description||pm.title||'';return res.status(200).json({platform:'instagram',type:'post',url:pm.url||target,title:pm.title||'Instagram post',description,caption:description,author:'',username:'',thumbnail:pm.image||'',mediaUrl:pm.video||'',mediaType:/\/(?:reel|reels|tv)\//i.test(target)?'video':'image',views:null,viewCount:null,likes:null,likeCount:null,metricsUnavailable:true,fetchFailed:true,authError:Number(e.code)===190,error:e.message||'Instagram embed request failed.',code:e.code||null,embedHtml:'',embedUrl:target,provider:'instagram'});}
const title=d.title||pm.title||'Instagram post';const description=d.description||pm.description||d.title||'';const thumb=d.thumbnail_url||pm.image||'';const mediaType=/\/(?:reel|reels|tv)\//i.test(target)?'video':'image';const mediaId=String(d.media_id||d.id||'');const media=mediaId?await fetchMedia(mediaId,clean(process.env.INSTAGRAM_ACCESS_TOKEN)):null;const caption=media?.caption||description;return res.status(200).json({platform:'instagram',type:media?.media_type||mediaType,url:media?.permalink||pm.url||target,id:media?.id||mediaId,mediaId:media?.id||mediaId,title:media?.caption?media.caption.split('\n')[0].slice(0,120):title,description:caption,caption,author:d.author_name||'',username:d.author_name||'',thumbnail:media?.thumbnail_url||media?.media_url||thumb,mediaUrl:media?.media_url||pm.video||'',mediaType:media?.media_type||mediaType,views:media?.view_count!=null?Number(media.view_count):null,viewCount:media?.view_count!=null?Number(media.view_count):null,likes:media?.like_count!=null?Number(media.like_count):null,likeCount:media?.like_count!=null?Number(media.like_count):null,comments:media?.comments_count!=null?Number(media.comments_count):null,embedHtml:d.html||'',embedUrl:target,metricsUnavailable:!media,provider:'instagram-oembed'});}catch(e){return res.status(400).json({error:e?.message||'Unable to fetch Instagram data.'});}}
