import crypto from 'node:crypto';
import {authorize as eugeneAuthorize,exchange as eugeneToken,revoke as eugeneRevoke,bootstrap as eugeneBootstrap} from '../eugene-card-oauth.js';
import {handleOAuth} from '../lib/oauth-provider.js';
import {handleOAuthAdmin} from '../lib/oauth-admin.js';
function config(){return{url:(process.env.SUPABASE_URL||"").replace(/\/$/,""),key:process.env.SUPABASE_SERVICE_ROLE_KEY||""}}
const RESOURCES={profiles:{select:'id,username,display_name,role,bio,avatar_url,skills,available,account_type,is_admin,socials',order:'created_at'},projects:{select:'id,owner_id,title,description,category,tags,thumbnail_url,media_url,media_type,published,featured,views,likes,created_at,slides',order:'created_at.desc'},services:{select:'id,owner_id,artist_id,title,description,category,tags,price_from,delivery_time,thumbnail_url,published,featured,views,add_ons,created_at,service_projects(project_id)',order:'created_at.desc'}};
const EVENT_TYPES=['view','like','save','share','open_artist','search'];
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const EUGENE_FIREBASE_API_KEY='AIzaSyCm13Nh6k6W9wsL0_OPpjKZNrbSg-pFsuA';
function sanitizeCommission(c){if(!c||typeof c!=='object')return null;const service_id=typeof c.service_id==='string'&&UUID_RE.test(c.service_id)?c.service_id:null,name=typeof c.name==='string'?c.name.trim().slice(0,100):'',email=typeof c.email==='string'?c.email.trim().slice(0,160):'',message=typeof c.message==='string'?c.message.trim().slice(0,4000):'',budget=typeof c.budget==='string'?c.budget.trim().slice(0,80):'',addon_titles=Array.isArray(c.addon_titles)?c.addon_titles.filter(x=>typeof x==='string').slice(0,10).map(x=>x.slice(0,120)):[];if(!service_id||!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!message)return null;return{service_id,name,email,message,budget,addon_titles}}
function sanitizeEvent(event){if(!event||typeof event!=='object')return null;const session_id=typeof event.session_id==='string'?event.session_id.slice(0,128):null;if(!session_id)return null;const event_type=typeof event.event_type==='string'?event.event_type:null;if(!EVENT_TYPES.includes(event_type))return null;let project_id=null;if(event.project_id!=null){if(typeof event.project_id!=='string'||!UUID_RE.test(event.project_id))return null;project_id=event.project_id}const category=typeof event.category==='string'?event.category.slice(0,64):null;const tags=event.metadata&&Array.isArray(event.metadata.tags)?event.metadata.tags.filter(t=>typeof t==='string').slice(0,20).map(t=>t.slice(0,64)):[];return{session_id,project_id,event_type,category,metadata:{tags}}}
function sanitizeSlide(s,i){if(!s||typeof s!=='object')return null;const type=['image','video','link'].includes(s.type)?s.type:'link',platform=typeof s.platform==='string'?s.platform.slice(0,24):null,url=typeof s.url==='string'?s.url.trim().slice(0,4000):'',title=typeof s.title==='string'?s.title.trim().slice(0,200):`Slide ${i+1}`,description=typeof s.description==='string'?s.description.trim().slice(0,4000):'',id=typeof s.id==='string'?s.id.slice(0,100):`${Date.now()}-${i}`;if(!url||!/^https?:\/\//i.test(url))return null;return{id,type,platform,url,title,description,position:i+1}}
async function userFromToken(url,key,token){if(!token)return null;const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});if(!r.ok)return null;return await r.json()}
async function isAdmin(url,key,userId){const r=await fetch(`${url}/rest/v1/profiles?select=id,is_admin&id=eq.${encodeURIComponent(userId)}&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});const rows=await r.json(),p=Array.isArray(rows)?rows[0]:null;return !!p&&p.is_admin===true}
async function toggleMember(req,res,url,key){const auth=String(req.headers.authorization||''),token=auth.startsWith('Bearer ')?auth.slice(7):'',user=await userFromToken(url,key,token);if(!user?.id)return res.status(401).json({error:'Sign in is required.'});if(!(await isAdmin(url,key,user.id)))return res.status(403).json({error:'Administrator access required.'});const targetId=String((req.body||{}).targetId||''),nextType=String((req.body||{}).nextType||'');if(!UUID_RE.test(targetId))return res.status(400).json({error:'Invalid member id.'});if(!['user','member'].includes(nextType))return res.status(400).json({error:'Invalid account type.'});const r=await fetch(`${url}/rest/v1/rpc/admin_set_account_type`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({p_target_id:targetId,p_account_type:nextType})}),text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)return res.status(400).json({error:body?.message||body?.error||body?.hint||'Unable to update member.'});return res.status(200).json(body||{success:true})}
async function saveProjectSlides(req,res,url,key){const auth=String(req.headers.authorization||''),token=auth.startsWith('Bearer ')?auth.slice(7):'',user=await userFromToken(url,key,token);if(!user?.id)return res.status(401).json({success:false,error:'Sign in is required.'});const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const projectId=String(body.projectId||''),title=String(body.title||'').trim();const raw=Array.isArray(body.slides)?body.slides:[];if(raw.length>100)return res.status(400).json({success:false,error:'A project can contain at most 100 slides.'});const slides=raw.map(sanitizeSlide).filter(Boolean);if(slides.length!==raw.length)return res.status(400).json({success:false,error:'One or more Slides are invalid.'});const headers={apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json'};let row=null;if(UUID_RE.test(projectId)){const r=await fetch(`${url}/rest/v1/projects?id=eq.${encodeURIComponent(projectId)}&owner_id=eq.${encodeURIComponent(user.id)}&select=id,owner_id&limit=1`,{headers});const rows=await r.json().catch(()=>[]);row=rows?.[0]||null}else if(title){const r=await fetch(`${url}/rest/v1/projects?owner_id=eq.${encodeURIComponent(user.id)}&title=eq.${encodeURIComponent(title)}&select=id,owner_id&order=created_at.desc&limit=1`,{headers});const rows=await r.json().catch(()=>[]);row=rows?.[0]||null}if(!row)return res.status(404).json({success:false,error:'Project was not found for the signed-in account.'});const updated=await fetch(`${url}/rest/v1/projects?id=eq.${encodeURIComponent(row.id)}&owner_id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',headers:{...headers,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({slides,updated_at:new Date().toISOString()})});const text=await updated.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=null}if(!updated.ok)return res.status(updated.status).json({success:false,error:data?.message||data?.error||'Project Slides database save failed.'});const saved=Array.isArray(data)?data[0]:data;return res.status(200).json({success:true,projectId:row.id,count:Array.isArray(saved?.slides)?saved.slides.length:slides.length,slides:saved?.slides||slides})}
function supabaseHeaders(key){return{apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json'}}
async function getEugeneConnection(url,key,userId){const r=await fetch(`${url}/rest/v1/eugene_card_connections?lunarist_user_id=eq.${encodeURIComponent(userId)}&select=eugene_uid,eugene_email,profile_url,connected_at,last_seen_at&limit=1`,{headers:supabaseHeaders(key)});const rows=await r.json().catch(()=>[]);return Array.isArray(rows)?rows[0]||null:null}
async function getOauthConnection(url,key,userId){const r=await fetch(`${url}/rest/v1/oauth_tokens?client_id=eq.eugene-card&lunarist_user_id=eq.${encodeURIComponent(userId)}&revoked_at=is.null&select=id,scope,created_at,last_used_at&order=created_at.desc&limit=1`,{headers:supabaseHeaders(key)});const rows=await r.json().catch(()=>[]);return Array.isArray(rows)?rows[0]||null:null}
async function verifyEugeneFirebaseToken(idToken){if(!idToken)return null;const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(EUGENE_FIREBASE_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken})});if(!r.ok)return null;const d=await r.json().catch(()=>null),u=Array.isArray(d?.users)?d.users[0]:null;return u?.localId?{uid:u.localId,email:u.email||null}:null}
async function eugeneConnection(req,res,url,key,user){const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const action=String(body.action||'');const headers={...supabaseHeaders(key),'Content-Type':'application/json'};if(req.method==='GET'){const connection=await getEugeneConnection(url,key,user.id);const grant=await getOauthConnection(url,key,user.id);const connected=!!connection||!!grant;if(connection)await fetch(`${url}/rest/v1/eugene_card_connections?lunarist_user_id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',headers,body:JSON.stringify({last_seen_at:new Date().toISOString()})});return res.status(200).json({connected,connection:connection||(grant?{connected_at:grant.created_at,last_seen_at:grant.last_used_at||grant.created_at}:null)})}if(action==='disconnect'){await fetch(`${url}/rest/v1/eugene_card_connections?lunarist_user_id=eq.${encodeURIComponent(user.id)}`,{method:'DELETE',headers:supabaseHeaders(key)});await fetch(`${url}/rest/v1/eugene_link_codes?lunarist_user_id=eq.${encodeURIComponent(user.id)}`,{method:'DELETE',headers:supabaseHeaders(key)});await fetch(`${url}/rest/v1/oauth_tokens?client_id=eq.eugene-card&lunarist_user_id=eq.${encodeURIComponent(user.id)}&revoked_at=is.null`,{method:'PATCH',headers,body:JSON.stringify({revoked_at:new Date().toISOString()})});return res.status(200).json({connected:false})}return res.status(400).json({error:'Invalid Eugene Card action.'})}
async function exchangeEugene(req,res,url,key){const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const code=String(body.code||'').trim(),idToken=String(body.firebase_id_token||'').trim();if(!/^[A-Za-z0-9_-]{20,200}$/.test(code)||!idToken)return res.status(400).json({error:'Invalid connection request.'});const firebaseUser=await verifyEugeneFirebaseToken(idToken);if(!firebaseUser)return res.status(401).json({error:'Eugene Card sign-in could not be verified.'});const now=new Date().toISOString();const r=await fetch(`${url}/rest/v1/eugene_link_codes?code=eq.${encodeURIComponent(code)}&expires_at=gt.${encodeURIComponent(now)}&select=id,lunarist_user_id&limit=1`,{headers:supabaseHeaders(key)});const rows=await r.json().catch(()=>[]),pending=Array.isArray(rows)?rows[0]:null;if(!pending)return res.status(400).json({error:'This Lunarist connection code is invalid or expired.'});const existing=await fetch(`${url}/rest/v1/eugene_card_connections?eugene_uid=eq.${encodeURIComponent(firebaseUser.uid)}&select=lunarist_user_id&limit=1`,{headers:supabaseHeaders(key)}),existingRows=await existing.json().catch(()=>[]),existingUser=Array.isArray(existingRows)?existingRows[0]:null;if(existingUser&&existingUser.lunarist_user_id!==pending.lunarist_user_id)return res.status(409).json({error:'This Eugene Card account is already connected to another Lunarist account.'});const headers={...supabaseHeaders(key),'Content-Type':'application/json'};await fetch(`${url}/rest/v1/eugene_link_codes?id=eq.${encodeURIComponent(pending.id)}`,{method:'DELETE',headers:supabaseHeaders(key)});const saved=await fetch(`${url}/rest/v1/eugene_card_connections`,{method:'POST',headers:{...headers,Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({lunarist_user_id:pending.lunarist_user_id,eugene_uid:firebaseUser.uid,eugene_email:firebaseUser.email,connected_at:now,last_seen_at:now})});if(!saved.ok)return res.status(500).json({error:'The Eugene Card connection could not be saved.'});return res.status(200).json({connected:true,eugene_email:firebaseUser.email||null})}
export default async function handler(req,res){const {url,key}=config();if(!url||!key)return res.status(503).json({error:'Supabase server credentials are not configured.'});const q=req.url.includes('?')?req.url.slice(req.url.indexOf('?')+1):'',params=new URLSearchParams(q),resource=params.get('resource')||req.query?.resource||'';try{
if(resource==='oauth-admin'){
  return await handleOAuthAdmin(req,res);
}
if(resource==='oauth')return await handleOAuth(req,res);
if(resource==='eugene-authorize')return await eugeneAuthorize(req,res,url,key);
if(resource==='eugene-token')return await eugeneToken(req,res,url,key);
if(resource==='eugene-revoke')return await eugeneRevoke(req,res,url,key);
if(resource==='eugene-session')return await eugeneBootstrap(req,res,url,key);
if(resource==='eugene'&&req.method==='POST'&&(req.body||{}).action==='exchange')return await exchangeEugene(req,res,url,key);
if(resource==='eugene'){const token=String(req.headers.authorization||'').startsWith('Bearer ')?String(req.headers.authorization).slice(7):'',user=await userFromToken(url,key,token);if(!user?.id)return res.status(401).json({error:'Sign in is required.'});return await eugeneConnection(req,res,url,key,user)}
if(req.method==='POST'&&(req.body||{}).action==='toggle-member')return await toggleMember(req,res,url,key);
if(req.method==='POST'&&(req.body||{}).action==='save-project-slides')return await saveProjectSlides(req,res,url,key);
if(req.method==='GET'){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');if(resource==='recommendations'){const sessionId=params.get('session_id')||'';if(!sessionId)return res.status(400).json({error:'session_id is required'});const limit=Math.min(20,Math.max(1,Number(params.get('limit')||5))),r=await fetch(`${url}/rest/v1/rpc/get_recommendations`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({p_session_id:sessionId,p_limit:limit})}),text=await r.text();res.status(r.status).setHeader('Content-Type','application/json');return res.send(text)}const def=RESOURCES[resource];if(!def)return res.status(400).json({error:'Use resource=profiles, resource=projects, resource=services, or resource=recommendations'});const out=new URLSearchParams({select:def.select,order:def.order});if(resource==='projects'||resource==='services')out.set('published','eq.true');if(resource==='profiles')out.set('or','(account_type.eq.member,is_admin.eq.true)');const r=await fetch(`${url}/rest/v1/${resource}?${out}`,{headers:{apikey:key,Authorization:`Bearer ${key}`}}),text=await r.text();res.status(r.status).setHeader('Content-Type','application/json');return res.send(text)}
if(req.method==='POST'){if((req.body||{}).commission){const c=sanitizeCommission(req.body.commission);if(!c)return res.status(400).json({error:'Invalid commission inquiry'});const r=await fetch(`${url}/rest/v1/commissions`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(c)}),text=await r.text();res.status(r.status);return text?res.send(text):res.end()}const event=sanitizeEvent((req.body||{}).event);if(!event)return res.status(400).json({error:'Invalid event'});const r=await fetch(`${url}/rest/v1/discovery_events`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(event)}),text=await r.text();res.status(r.status);return text?res.send(text):res.end()}return res.status(405).json({error:'Method not allowed'})}catch(e){console.error(e);return res.status(500).json({error:'Supabase request failed'})}}