function config(){return{url:(process.env.SUPABASE_URL||'').replace(/\/$/,''),key:process.env.SUPABASE_SERVICE_ROLE_KEY||''}}
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function token(req){const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7):''}
async function userFromToken(url,key,t){if(!t)return null;const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${t}`}});if(!r.ok)return null;return r.json()}
function cleanSlides(input){if(!Array.isArray(input))return [];return input.slice(0,100).map((s,i)=>{const x=s&&typeof s==='object'?s:{};return{id:typeof x.id==='string'?x.id.slice(0,120):`${Date.now()}-${i}`,type:['image','video','link'].includes(x.type)?x.type:'link',platform:typeof x.platform==='string'?x.platform.slice(0,30):null,url:typeof x.url==='string'?x.url.trim().slice(0,2000):'',title:typeof x.title==='string'?x.title.slice(0,200):`Slide ${i+1}`,description:typeof x.description==='string'?x.description.slice(0,4000):'',position:i+1}}).filter(x=>x.url)}
export default async function handler(req,res){const {url,key}=config();if(!url||!key)return res.status(503).json({error:'Supabase server credentials are not configured.'});const t=token(req),user=await userFromToken(url,key,t);if(!user?.id)return res.status(401).json({error:'Sign in is required.'});try{
 if(req.method==='GET'){
   const id=String(req.query?.projectId||'');if(!UUID_RE.test(id))return res.status(400).json({error:'Invalid project id.'});
   const r=await fetch(`${url}/rest/v1/projects?select=id,title,slides&owner_id=eq.${encodeURIComponent(user.id)}&id=eq.${encodeURIComponent(id)}&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});const rows=await r.json();if(!r.ok)return res.status(r.status).json({error:'Unable to load project slides.'});if(!rows[0])return res.status(404).json({error:'Project not found.'});return res.status(200).json({projectId:id,slides:Array.isArray(rows[0].slides)?rows[0].slides:[]});
 }
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 const body=req.body||{},title=String(body.title||'').trim().slice(0,200),requestedId=String(body.projectId||'');let id=UUID_RE.test(requestedId)?requestedId:null;
 if(id){const check=await fetch(`${url}/rest/v1/projects?select=id&owner_id=eq.${encodeURIComponent(user.id)}&id=eq.${encodeURIComponent(id)}&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});const rows=await check.json();if(!rows[0])return res.status(404).json({error:'Project not found or not owned by you.'});}
 if(!id){if(!title)return res.status(400).json({error:'Project title is required.'});const find=await fetch(`${url}/rest/v1/projects?select=id&owner_id=eq.${encodeURIComponent(user.id)}&title=eq.${encodeURIComponent(title)}&order=created_at.desc&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});const rows=await find.json();if(!rows[0])return res.status(404).json({error:'Project has not been created yet.'});id=rows[0].id}
 const slides=cleanSlides(body.slides);const r=await fetch(`${url}/rest/v1/projects?id=eq.${encodeURIComponent(id)}&owner_id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({slides,updated_at:new Date().toISOString()})});const text=await r.text();let rows;try{rows=JSON.parse(text)}catch{rows=[]}if(!r.ok)return res.status(r.status).json({error:'Database rejected the Slides update.',details:rows});if(!Array.isArray(rows)||!rows[0])return res.status(500).json({error:'Database did not return the updated project.'});const stored=Array.isArray(rows[0].slides)?rows[0].slides:[];return res.status(200).json({success:true,projectId:id,count:stored.length,slides:stored});
}catch(e){console.error('[project-slides]',e);return res.status(500).json({error:'Project Slides request failed.'})}}
