// Lunarist X view-count resolver.
// Resolves X's current public TweetResultByRestId query id from the web bundle,
// then reads the public view count. This is used only when /api/x cannot supply views.
const BEARER='Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA';
const FALLBACK_QUERY_IDS=['zAz9764BcLZOJ0JU2wrd1A','7xflPyRiUxGVbJd4uWmbfg','SgZWKwvBiOKrSC0QeOGvXw'];
function clean(v){return String(v||'').trim().replace(/^Bearer\s+/i,'').trim();}
function parse(raw){const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);const h=u.hostname.toLowerCase().replace(/^www\./,'');if(!['x.com','twitter.com','mobile.twitter.com'].includes(h))throw new Error('That does not look like an X post URL.');const m=u.pathname.match(/\/(?:[^/]+)\/status\/(\d+)/i);if(!m)throw new Error('That does not look like an X post URL.');return m[1];}
function features(){return{creator_subscriptions_tweet_preview_api_enabled:true,premium_content_api_read_enabled:false,communities_web_enable_tweet_community_results_fetch:true,c9s_tweet_anatomy_moderator_badge_enabled:true,articles_preview_enabled:true,responsive_web_edit_tweet_api_enabled:true,graphql_is_translatable_rweb_tweet_is_translatable_enabled:true,view_counts_everywhere_api_enabled:true,longform_notetweets_consumption_enabled:true,responsive_web_twitter_article_tweet_consumption_enabled:true,freedom_of_speech_not_reach_fetch_enabled:true,standardized_nudges_misinfo:true,tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled:true,longform_notetweets_rich_text_read_enabled:true,longform_notetweets_inline_media_enabled:false,verified_phone_label_enabled:false,responsive_web_graphql_skip_user_profile_image_extensions_enabled:false,responsive_web_graphql_timeline_navigation_enabled:true,responsive_web_enhance_cards_enabled:false};}
async function currentQueryId(){try{const r=await fetch('https://x.com/',{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,application/xhtml+xml'}});if(!r.ok)return null;const html=await r.text();const main=html.match(/https:\/\/abs\.twimg\.com\/responsive-web\/client-web\/main\.([A-Za-z0-9_-]+)\.js/)||html.match(/\/responsive-web\/client-web\/main\.([A-Za-z0-9_-]+)\.js/);if(!main)return null;const r2=await fetch(`https://abs.twimg.com/responsive-web/client-web/main.${main[1]}.js`,{headers:{'User-Agent':'Mozilla/5.0','Accept':'*/*'}});if(!r2.ok)return null;const js=await r2.text();const m=js.match(/queryId:\"([^\"]+)\",operationName:\"TweetResultByRestId\"/)||js.match(/operationName:\"TweetResultByRestId\"[\s\S]{0,400}?queryId:\"([^\"]+)\"/);return m?.[1]||null;}catch{return null;}}
async function request(id,qid){try{const u=new URL(`https://x.com/i/api/graphql/${qid}/TweetResultByRestId`);u.searchParams.set('variables',JSON.stringify({tweetId:String(id),withCommunity:false,includePromotedContent:false,withVoice:false}));u.searchParams.set('features',JSON.stringify(features()));u.searchParams.set('fieldToggles',JSON.stringify({withArticleRichContentState:true,withArticlePlainText:false,withGrokAnalyze:false,withDisallowedReplyControls:false}));const r=await fetch(u,{headers:{Authorization:clean(BEARER),'x-twitter-active-user':'yes','x-twitter-client-language':'en','User-Agent':'Mozilla/5.0','Accept':'application/json','Referer':'https://x.com/'} });if(!r.ok)return null;const j=await r.json().catch(()=>null);const raw=j?.data?.tweetResult?.result;const t=raw?.tweet||raw;if(!t)return null;const legacy=t.legacy||{};const candidates=[t.views?.count,t.views?.countString,legacy.views?.count,legacy.view_count];for(const v of candidates){const n=Number(String(v??'').replace(/,/g,''));if(Number.isFinite(n)&&n>=0)return n;}return null;}catch{return null;}}
export default async function handler(req,res){try{const id=parse(req.query?.url||req.body?.url||'');const dynamic=await currentQueryId();const ids=[dynamic,...FALLBACK_QUERY_IDS].filter(Boolean);for(const qid of ids){const views=await request(id,qid);if(Number.isFinite(views))return res.status(200).json({ok:true,id,views,source:'x-web'});}return res.status(200).json({ok:false,id,views:null,source:'x-web'});}catch(e){return res.status(400).json({ok:false,error:e?.message||'Unable to fetch X views.'});}}
