// Lunarist X fetcher + server-authoritative project metric sync.
// Uses the official X API when available, then X's public syndication feed as a read-only fallback.
function clean(v){return String(v||'').trim().replace(/^['"]|['"]$/g,'').replace(/^Bearer\s+/i,'').trim();}
function parse(raw){const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);const h=u.hostname.toLowerCase().replace(/^www\./,'');if(!['x.com','twitter.com','mobile.twitter.com'].includes(h))throw new Error('That does not look like an X post URL.');const m=u.pathname.match(/\/(?:[^/]+)\/status\/(\d+)/i);if(!m)throw new Error('That does not look like an X post URL.');return{id:m[1],original:u.toString()};}
function usageError(status,d){const s=JSON.stringify(d||{}).toLowerCase();return status===429||/usage.?cap|credits?.?deplet|credit.?deplet|quota|billing|spend.?limit|rate.?limit/.test(s);}
async function oembed(url){const u=new URL('https://publish.x.com/oembed');u.searchParams.set('url',url);u.searchParams.set('omit_script','1');const r=await fetch(u);const d=await r.json().catch(()=>({}));return r.ok?d:null;}
async function syndication(id){try{const r=await fetch(`https://cdn.syndication.twimg.com/tweet-result?id=${encodeURIComponent(id)}&token=0`,{headers:{Accept:'application/json'}});if(!r.ok)return null;const d=await r.json().catch(()=>null);return d&&d.id_str?d:null;}catch{return null;}}
function textFromEmbedHtml(html){if(!html)return '';const m=String(html).match(/<p[^>]*>([\s\S]*?)<\/p>/i);if(!m)return '';return m[1].replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'\"').replace(/&#39;/g,"'").replace(/&mdash;/g,'—').replace(/&nbsp;/g,' ').trim();}
async function fetchPost(id,token){const u=new URL(`https://api.x.com/2/tweets/${id}`);u.searchParams.set('tweet.fields','created_at,public_metrics,author_id,attachments,text');u.searchParams.set('expansions','author_id,attachments.media_keys');u.searchParams.set('user.fields','name,username,profile_image_url');u.searchParams.set('media.fields','url,preview_image_url,type,width,height,alt_text,public_metrics,duration_ms,variants');const r=await fetch(u,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));return{r,d};}
function normalizeMetrics(d){const t=d.data||{},tm=t.public_metrics||{},author=(d.includes?.users||[])[0]||{},media=(d.includes?.media||[])[0]||{},mm=media.public_metrics||{};const isVideo=media.type==='video'||media.type==='animated_gif';let directVideoUrl='';if(isVideo&&Array.isArray(media.variants)){const mp4s=media.variants.filter(v=>v.content_type==='video/mp4').sort((a,b)=>(b.bitrate||0)-(a.bitrate||0));if(mp4s.length)directVideoUrl=mp4s[0].url;}const videoViews=isVideo&&mm.view_count!=null?Number(mm.view_count):null;const impressions=tm.impression_count!=null?Number(tm.impression_count):null;const views=videoViews!=null?videoViews:impressions;const likes=tm.like_count!=null?Number(tm.like_count):null;const description=t.text||'';return{platform:'x',type:'post',url:`https://x.com/${author.username||'i'}/status/${t.id||''}`,id:t.id||'',title:description?description.split('\n')[0].slice(0,120):'X post',description,text:description,author:author.name||'',username:author.username||'',thumbnail:media.preview_image_url||media.url||'',mediaUrl:directVideoUrl||media.url||'',mediaType:directVideoUrl?'video':(media.type||''),createdAt:t.created_at||null,views:Number.isFinite(views)?views:null,viewCount:Number.isFinite(views)?views:null,likes:Number.isFinite(likes)?likes:null,likeCount:Number.isFinite(likes)?likes:null,replies:tm.reply_count!=null?Number(tm.reply_count):null,reposts:tm.retweet_count!=null?Number(tm.retweet_count):null,quotes:tm.quote_count!=null?Number(tm.quote_count):null,bookmarks:tm.bookmark_count!=null?Number(tm.bookmark_count):null,publicMetrics:tm,mediaPublicMetrics:mm};}
function normalizeSyndication(d,id,embed){const text=d.text||textFromEmbedHtml(embed?.html)||'';const likes=Number.isFinite(Number(d.favorite_count))?Number(d.favorite_count):null;const replies=Number.isFinite(Number(d.conversation_count))?Number(d.conversation_count):null;const reposts=Number.isFinite(Number(d.retweet_count))?Number(d.retweet_count):null;const author=d.user||{};const media=(d.mediaDetails||[])[0]||{};const thumb=media.media_url_https||media.thumbnail_url||'';return{platform:'x',type:'post',url:`https://x.com/${author.screen_name||'i'}/status/${id}`,id:String(id),title:text?text.split('\n')[0].slice(0,120):'X post',description:text,text,author:author.name||embed?.author_name||'',username:author.screen_name||'',thumbnail:thumb,mediaUrl:'',mediaType:'',createdAt:d.created_at||null,views:null,viewCount:null,likes,likeCount:likes,replies,reposts,quotes:Number.isFinite(Number(d.quote_count))?Number(d.quote_count):null,bookmarks:null,publicMetrics:{like_count:likes,reply_count:replies,retweet_count:reposts,quote_count:Number.isFinite(Number(d.quote_count))?Number(d.quote_count):null},mediaPublicMetrics:{},metricsUnavailable:false,quotaLimited:true,metricsSource:'x-syndication',embedHtml:embed?.html||'',embedUrl:`https://x.com/i/status/${id}`};}
async function getFresh(id,token,embed){if(token){const {r,d}=await fetchPost(id,token);if(r.ok)return{data:normalizeMetrics(d),official:true};if(!usageError(r.status,d))return{error:d.detail||d.title||d.errors?.[0]?.message||'X API request failed.'};}const s=await syndication(id);if(s)return{data:normalizeSyndication(s,id,embed),official:false};const fallbackText=textFromEmbedHtml(embed?.html);return{data:{platform:'x',type:'post',url:`https://x.com/i/status/${id}`,id,title:fallbackText?fallbackText.split('\n')[0].slice(0,120):(embed?.title||'X post'),description:fallbackText,text:fallbackText,author:embed?.author_name||'',username:'',thumbnail:'',mediaUrl:'',mediaType:'',views:null,likes:null,replies:null,reposts:null,metricsUnavailable:true,quotaLimited:true,embedHtml:embed?.html||'',embedUrl:`https://x.com/i/status/${id}`,notice:'X metrics are unavailable right now.'},official:false};}
async function syncProject(projectId,xId,token){const base=clean(process.env.SUPABASE_URL),key=clean(process.env.SUPABASE_SERVICE_ROLE_KEY);if(!base||!key||!projectId||!xId)return false;const headers={apikey:key,Authorization:`Bearer ${key}`,Accept:'application/json'};const lookup=await fetch(`${base}/rest/v1/projects?id=eq.${encodeURIComponent(projectId)}&select=id,media_url`,{headers});if(!lookup.ok)return false;const rows=await lookup.json().catch(()=>[]);const row=rows?.[0];if(!row||!parseIdFromAny(row.media_url,xId))return false;const embed=await oembed(`https://x.com/i/status/${xId}`);const fresh=await getFresh(xId,token,embed);if(!fresh.data)return false;const patch={};if(Number.isFinite(Number(fresh.data.likes)))patch.likes=Math.max(0,Math.floor(Number(fresh.data.likes)));if(Number.isFinite(Number(fresh.data.views)))patch.views=Math.max(0,Math.floor(Number(fresh.data.views)));if(!Object.keys(patch).length)return false;const updated=await fetch(`${base}/rest/v1/projects?id=eq.${encodeURIComponent(projectId)}`,{method:'PATCH',headers:{...headers,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});return updated.ok;}
function parseIdFromAny(url,xId){try{return parse(url).id===String(xId);}catch{return false;}}
export default async function handler(req,res){try{const token=clean(process.env.X_BEARER_TOKEN);if(req.method==='POST'){const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});const projectId=String(body.projectId||''),xId=String(body.xId||'');if(!projectId||!xId)return res.status(400).json({ok:false,error:'projectId and xId are required.'});const ok=await syncProject(projectId,xId,token);return res.status(ok?200:400).json({ok});}
const parsed=parse(req.query?.url||req.body?.url||'');const embed=await oembed(`https://x.com/i/status/${parsed.id}`);const fresh=await getFresh(parsed.id,token,embed);if(fresh.error)return res.status(502).json({error:fresh.error});return res.status(200).json({...fresh.data,embedHtml:fresh.data.embedHtml||embed?.html||'',embedUrl:`https://x.com/i/status/${parsed.id}`});}catch(e){return res.status(400).json({error:e?.message||'Unable to fetch X data.'});}}
