name: Package Lunarist Member Guideline
on:
  push:
    branches: [main]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create ZIP
        run: |
          cd "$GITHUB_WORKSPACE"
          zip -qr /tmp/Lunarist-Member-Guideline-Website.zip . -x ".git/*" "*.zip"
      - uses: actions/upload-artifact@v4
        with:
          name: Lunarist-Member-Guideline-Website
          path: /tmp/Lunarist-Member-Guideline-Website.zip
